# Generated by Django 3.1.7 on 2021-03-27 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_auto_20210327_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='RateScore',
        ),
        migrations.RenameField(
            model_name='ratescore',
            old_name='rating',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
