# Generated by Django 3.1.7 on 2021-05-19 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210329_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
